// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjnX6aE_rr_CtkXrBh1_ldweH2R1inO0I',
    appId: '1:547345619181:web:03d800ae3ca56d200854e4',
    messagingSenderId: '547345619181',
    projectId: 'fruits-hub-2a1bf',
    authDomain: 'fruits-hub-2a1bf.firebaseapp.com',
    storageBucket: 'fruits-hub-2a1bf.firebasestorage.app',
    measurementId: 'G-GM2KZ4HCHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWjEi6sRiKIlrQ3ElR2wRlFZlDmlxcxos',
    appId: '1:547345619181:android:ea2133123963652e0854e4',
    messagingSenderId: '547345619181',
    projectId: 'fruits-hub-2a1bf',
    storageBucket: 'fruits-hub-2a1bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzPzmq2y-RktsLxLI84PTT5Y4EwHimRYI',
    appId: '1:547345619181:ios:64f46c7a6b5561ed0854e4',
    messagingSenderId: '547345619181',
    projectId: 'fruits-hub-2a1bf',
    storageBucket: 'fruits-hub-2a1bf.firebasestorage.app',
    androidClientId: '547345619181-4ovtjglpecgge2qls1f0ero61t2930qn.apps.googleusercontent.com',
    iosClientId: '547345619181-lc5u351uvsh5ssne36ucvk388v9frlr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzPzmq2y-RktsLxLI84PTT5Y4EwHimRYI',
    appId: '1:547345619181:ios:64f46c7a6b5561ed0854e4',
    messagingSenderId: '547345619181',
    projectId: 'fruits-hub-2a1bf',
    storageBucket: 'fruits-hub-2a1bf.firebasestorage.app',
    androidClientId: '547345619181-4ovtjglpecgge2qls1f0ero61t2930qn.apps.googleusercontent.com',
    iosClientId: '547345619181-lc5u351uvsh5ssne36ucvk388v9frlr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjnX6aE_rr_CtkXrBh1_ldweH2R1inO0I',
    appId: '1:547345619181:web:287be30e526be0370854e4',
    messagingSenderId: '547345619181',
    projectId: 'fruits-hub-2a1bf',
    authDomain: 'fruits-hub-2a1bf.firebaseapp.com',
    storageBucket: 'fruits-hub-2a1bf.firebasestorage.app',
    measurementId: 'G-DM1YE2PJYN',
  );
}
